In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Telco-Customer-Churn2.csv to Telco-Customer-Churn2.csv

In [ ]:
import pandas as pd
df= pd.read_csv("Telco-Customer-Churn2.csv")
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,4546-FOKWR,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [ ]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [ ]:
df = df.dropna(subset=['TotalCharges'])

In [ ]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(22)

In [ ]:
del df['customerID']

In [ ]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
df[['Churn','Partner','Dependents','PhoneService','PaperlessBilling']]=df[['Churn','Partner','Dependents','PhoneService','PaperlessBilling']].replace({'Yes':1,'No':0})

/tmp/ipython-input-3191615114.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['Churn','Partner','Dependents','PhoneService','PaperlessBilling']]=df[['Churn','Partner','Dependents','PhoneService','PaperlessBilling']].replace({'Yes':1,'No':0})

In [ ]:
df.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,Male,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,Male,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,Male,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1
5,Female,0,0,0,8,1,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,99.65,820.50,1
6,Male,0,0,1,22,1,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,1,Credit card (automatic),89.10,1949.40,0
7,Female,0,0,0,10,0,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,0,Mailed check,29.75,301.90,0
8,Female,0,1,0,28,1,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,1,Electronic check,104.80,3046.05,1
9,Male,0,0,1,62,1,No,DSL,Yes,Yes,No,No,No,No,One year,0,Bank transfer (automatic),56.15,3487.95,0

In [ ]:
y = df['Churn']
X = df.drop('Churn', axis=1)

In [ ]:
X_Encoded = pd.get_dummies(X, drop_first=False)

In [ ]:
X_Encoded.head(10)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,gender_Female,gender_Male,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,1,29.85,29.85,True,False,...,True,False,False,True,False,False,False,False,True,False
1,0,0,0,34,1,0,56.95,1889.50,False,True,...,True,False,False,False,True,False,False,False,False,True
2,0,0,0,2,1,1,53.85,108.15,False,True,...,True,False,False,True,False,False,False,False,False,True
3,0,0,0,45,0,0,42.30,1840.75,False,True,...,True,False,False,False,True,False,True,False,False,False
4,0,0,0,2,1,1,70.70,151.65,True,False,...,True,False,False,True,False,False,False,False,True,False
5,0,0,0,8,1,1,99.65,820.50,True,False,...,False,False,True,True,False,False,False,False,True,False
6,0,0,1,22,1,1,89.10,1949.40,False,True,...,True,False,False,True,False,False,False,True,False,False
7,0,0,0,10,0,0,29.75,301.90,True,False,...,True,False,False,True,False,False,False,False,False,True
8,0,1,0,28,1,1,104.80,3046.05,True,False,...,False,False,True,True,False,False,False,False,True,False
9,0,0,1,62,1,0,56.15,3487.95,False,True,...,True,False,False,False,True,False,True,False,False,False

In [ ]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
final_df = pd.concat([X_Encoded, y], axis=1)

In [ ]:
final_df.head(10)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,gender_Female,gender_Male,...,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
0,0,1,0,1,0,1,29.85,29.85,True,False,...,False,False,True,False,False,False,False,True,False,0
1,0,0,0,34,1,0,56.95,1889.50,False,True,...,False,False,False,True,False,False,False,False,True,0
2,0,0,0,2,1,1,53.85,108.15,False,True,...,False,False,True,False,False,False,False,False,True,1
3,0,0,0,45,0,0,42.30,1840.75,False,True,...,False,False,False,True,False,True,False,False,False,0
4,0,0,0,2,1,1,70.70,151.65,True,False,...,False,False,True,False,False,False,False,True,False,1
5,0,0,0,8,1,1,99.65,820.50,True,False,...,False,True,True,False,False,False,False,True,False,1
6,0,0,1,22,1,1,89.10,1949.40,False,True,...,False,False,True,False,False,False,True,False,False,0
7,0,0,0,10,0,0,29.75,301.90,True,False,...,False,False,True,False,False,False,False,False,True,0
8,0,1,0,28,1,1,104.80,3046.05,True,False,...,False,True,True,False,False,False,False,True,False,1
9,0,0,1,62,1,0,56.15,3487.95,False,True,...,False,False,False,True,False,True,False,False,False,0

In [ ]:
final_df.dtypes

SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                       int64
PhoneService                                 int64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
gender_Female                                 bool
gender_Male                                   bool
MultipleLines_No                              bool
MultipleLines_No phone service                bool
MultipleLines_Yes                             bool
InternetService_DSL                           bool
InternetService_Fiber optic                   bool
InternetService_No                            bool
OnlineSecurity_No                             bool
OnlineSecurity_No internet service            bool
OnlineSecurity_Yes                            bool
OnlineBackup_No                               bool
OnlineBackup_No internet service              bool
OnlineBackup_Yes                              bool
DeviceProtection_No                           bool
DeviceProtection_No internet service          bool
DeviceProtection_Yes                          bool
TechSupport_No                                bool
TechSupport_No internet service               bool
TechSupport_Yes                               bool
StreamingTV_No                                bool
StreamingTV_No internet service               bool
StreamingTV_Yes                               bool
StreamingMovies_No                            bool
StreamingMovies_No internet service           bool
StreamingMovies_Yes                           bool
Contract_Month-to-month                       bool
Contract_One year                             bool
Contract_Two year                             bool
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
Churn                                        int64
dtype: object

In [ ]:
final_df=final_df.astype(int)

In [ ]:
final_df.dtypes

SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                     int64
PhoneService                               int64
PaperlessBilling                           int64
MonthlyCharges                             int64
TotalCharges                               int64
gender_Female                              int64
gender_Male                                int64
MultipleLines_No                           int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_DSL                        int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No                          int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No                            int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No                        int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No                             int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No                             int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No                         int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_Month-to-month                    int64
Contract_One year                          int64
Contract_Two year                          int64
PaymentMethod_Bank transfer (automatic)    int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
Churn                                      int64
dtype: object

In [ ]:
final_df.head(10)

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,gender_Female,gender_Male,...,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
0,0,1,0,1,0,1,29,29,1,0,...,0,0,1,0,0,0,0,1,0,0
1,0,0,0,34,1,0,56,1889,0,1,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,2,1,1,53,108,0,1,...,0,0,1,0,0,0,0,0,1,1
3,0,0,0,45,0,0,42,1840,0,1,...,0,0,0,1,0,1,0,0,0,0
4,0,0,0,2,1,1,70,151,1,0,...,0,0,1,0,0,0,0,1,0,1
5,0,0,0,8,1,1,99,820,1,0,...,0,1,1,0,0,0,0,1,0,1
6,0,0,1,22,1,1,89,1949,0,1,...,0,0,1,0,0,0,1,0,0,0
7,0,0,0,10,0,0,29,301,1,0,...,0,0,1,0,0,0,0,0,1,0
8,0,1,0,28,1,1,104,3046,1,0,...,0,1,1,0,0,0,0,1,0,1
9,0,0,1,62,1,0,56,3487,0,1,...,0,0,0,1,0,1,0,0,0,0

In [ ]:
cols_to_drop = ['gender_Male',
'MultipleLines_No phone service',
'OnlineSecurity_No internet service',
'OnlineBackup_No internet service',
'DeviceProtection_No internet service',
'TechSupport_No internet service',
'StreamingTV_No internet service',
'StreamingMovies_No internet service',
'InternetService_No',

]


final_df = final_df.drop(columns=cols_to_drop, errors='ignore')

In [ ]:
final_df.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'gender_Female',
       'MultipleLines_No', 'MultipleLines_Yes', 'InternetService_DSL',
       'InternetService_Fiber optic', 'OnlineSecurity_No',
       'OnlineSecurity_Yes', 'OnlineBackup_No', 'OnlineBackup_Yes',
       'DeviceProtection_No', 'DeviceProtection_Yes', 'TechSupport_No',
       'TechSupport_Yes', 'StreamingTV_No', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_Yes', 'Contract_Month-to-month',
       'Contract_One year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'Churn'],
      dtype='object')

In [ ]:
final_df.shape

(7032, 31)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

final_df.to_pickle('/content/drive/MyDrive/analysis.pkl')

Mounted at /content/drive

NameError: name 'final_df' is not defined